defaults:
  - dataset: imagenet 
  - detector: gdino_tiny  # gdino_tiny , gt_middle, gt 
  - segmentation: sam1 # sam2 in the future
  - class_list : categories # categories, general, dataset_defaults
  #dataset default too large for gdino_tiny and imagenet
  
  # disables logging and outputs
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
  
 
batch_size: 10 # h4, b5 on RTX4000, b8,h6 on A100 
    # 14 fits well with gt (38 GB) but sometimes overflows?
max_batch: 4 # None or integer. None for the whole dataset
save_results: True # whether to save anything at all
print_results: True
save_path: ./out/pipeline_results/
evaluator: 
  add_inverse : False
  # try to add an inverse mask to and maybe correct some of the images, where sam selects a bad object
  save_results_per_image: True
  # whether to save detected boxes and masks per image, or just aggregate results overall


# disable making directories for the outputs 
hydra:  
  output_subdir: null  
  run:  
    dir: .

