defaults:
  - dataset: coco # No alternative currently 
  - detector: gdino_tiny  # gdino_tiny , gt_detector_middle, gt_detector
  - segmentation: sam1 # sam2 in the future

  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
 
batch_size: 6  # h4, b6 on RTX4000, b8,h6 on A100
max_batch: 10 # None or integer
save_results: False
print_results: True
save_path: ./out/pipeline_results/


#disable saving results and logging
hydra:  
  output_subdir: null  
  run:  
    dir: .

