segmentation: 
  name: sam1 #sam1, sam2, None
  model: b  # b,h = base or huge

detector:
  name:  gt boxes middle
# gt boxes , gt boxes middle, None
 
dataset: 
  name: coco 
  split: val  # train or val
  year: 2017


batchsize: 6  # h4, b6 on RTX4000, b8,h6 on A100
max_batch: 2 # None or integer
save_results: False
print_results: True
save_path: ./out/pipeline_results/


hydra:  #disable output, saving our way
  output_subdir: null  
  run:  
    dir: .

defaults:  
- _self_  
- override hydra/hydra_logging: disabled  
- override hydra/job_logging: disabled  