defaults:
  - dataset: coco # No alternative currently 
  - detector: gt  # gdino_tiny , gt_middle, gt 
  - segmentation: sam1 # sam2 in the future
  - class_list : dataset_defaults # categories, general, dataset_defaults

  # disables logging and outputs
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
  
 
batch_size: 8 # h4, b5 on RTX4000, b8,h6 on A100
max_batch: None # None or integer
save_results: True
print_results: True
save_path: ./out/pipeline_results/
evaluator: 
  add_inverse : True
  # try to add an inverse mask to and maybe correct some of the images


# disable making directories for the outputs 
hydra:  
  output_subdir: null  
  run:  
    dir: .

