defaults:
  - dataset: imagenet # imagenet or coco
  - detector: gdino_full  # gdino_tiny , gdino_full, gt_middle, gt 
  - segmentation: sam1 # sam2 in the future
  - class_list : dataset_defaults # categories, general, dataset_defaults
  
  # disables logging and outputs
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
  
 
batch_size: 8
max_batch:  None # None or integer. None for the whole dataset
save_results: True # whether to save anything at all, if False, the toher options are irrelevant
print_results: False
save_path:  /datagrid/fix_in/detection/ #./out/pipeline_results/
evaluator: 
  add_inverse: False
  # try to add an inverse mask to and maybe correct some of the images, where sam selects a bad object from the box
  save_results_per_image: True 
  save_matches_to_gt: False 
  # whether to save detected boxes and masks per image, or just aggregate results overall and save those


# disable making directories for the outputs 
hydra:  
  output_subdir: null  
  run:  
    dir: .

