split: train  # train or val
year: 2017 #2014 or 2017

#dont change, loads the appropriate class
class_name: CocoLoader
split_fn: get_coco_split
root: /mnt/vrg2/imdec/datasets/COCO #root where coco is loaded